[admin]
name = "PI-Victor"

[[Labels]]
name = "approved"
color = "#324C33"
description = "A PR that has been approved"

[[Labels]]
name = "do-not-merge"
color = "#992B27"
description = "A PR that should not be merged"

[[Labels]]
name = "needs-ok-to-test"
color = "#A65F14"
description = "A PR from an outside contributor that needs the ok-to-test label to run the CI pipeline"

[[Labels]]
name = "ok-to-test"
color = "#BBF9C0"
description = "A PR that can be tested"

[[Labels]]
name = "dependencies"
color = "#6DA6F6"
description = "A PR that bumps dependencies"

[[Labels]]
name = "area/tests"
color = "#6DA6F6"
description = "A PR that contains tests changes"

[[Labels]]
name = "area/plugins"
color = "#6DA6F6"
description = "A PR that contains plugin changes"

[[Labels]]
name = "area/infrastructure"
color = "#6DA6F6"
description = "A PR that contains plugin changes"

[[Labels]]
name = "kind/chore"
color = "#424851"
description = "A PR that handles misc changes"

[[Labels]]
name = "kind/documentation"
color = "#424851"
description = "A PR that modifies or updates documentation"

[[Labels]]
name = "kind/feature"
color = "#424851"
description = "A PR that introduces a new feature"

[[Labels]]
name = "kind/bug"
color = "#F4BBBA"
description = "A PR or issue that reports or fixes a bug"

[[Labels]]
name = "kind/failing-test"
color = "#F4BBBA"
description = "A PR or issue that reports or fixes a failing test"

[[Labels]]
name = "lifecycle/stale"
color = "#AF9185"
description = "A PR or issue that is old and has no activity"

[[Labels]]
name = "lifecycle/rotten"
color = "#424851"
description = "A PR or issue that is old and already has the lifecycle/stale will be auto-closed"

[[Labels]]
name = "needs-triage"
color = "#424851"
description = "A PR or issue that has not been triaged"

[[Labels]]
name = "triage/accepted"
color = "#324C33"
description = "A PR or issue that has been triaged and can be worked on"

[[Labels]]
name = "size/S"
color = "#6EED47"
description = "A PR that contains between less than 50 lines of code"

[[Labels]]
name = "size/M"
color = "#464230"
description = "A PR that contains between less than 200 lines of code"

[[Labels]]
name = "size/L"
color = "#F4BBBA"
description = "A PR that contains over 200 lines of code"
